# Use a base image with Node.js pre-installed
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code to the working directory
COPY . .

# Build the project
RUN npm run build

# Install serve globally
RUN npm install -g serve

# Set the command to run when the container starts
CMD serve -s build

# Expose the container's port
EXPOSE 5000

