---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/self_hosted/containers/jellyfin:/config
      - /mnt/hgfs/SharedKali:/data/media
    ports:
      - 8096:8096
    restart: unless-stopped
