version: '3'
services:
  react-ui:
    build:
      context: ./portfolio-react
    ports:
      - "3000:3000"
    stdin_open: true # in the docker-compose file to start in an interactive mode.
    volumes:
       - ./portfolio-react:/opt/self_hosted/containers/reactjs/portfolio-react
       - /opt/self_hosted/containers/reactjs/portfolio-reactjs/node_modules
